### ISSUE TITLE
TypeError: Cannot read property 'pop' of undefined at merkle-patricia-tree

### ISSUE THREAD

**Issue by bingen** [aragon/aragon-cli#106]
I'm having this problem when cli is trying to start a local chain:
```
% aragon run --no-client                                                                                                                                     /home/bingen/.nvm/versions/node/v9.4.0/lib/node_modules/@aragon/cli/node_modules/merkle-patricia-tree/baseTrie.js:360
  var lastNode = stack.pop()
                       ^

TypeError: Cannot read property 'pop' of undefined
    at CheckpointTrie.Trie._updateNode (/home/bingen/.nvm/versions/node/v9.4.0/lib/node_modules/@aragon/cli/node_modules/merkle-patricia-tree/baseTrie.js:360:24)
    at /home/bingen/.nvm/versions/node/v9.4.0/lib/node_modules/@aragon/cli/node_modules/merkle-patricia-tree/baseTrie.js:107:16
    at /home/bingen/.nvm/versions/node/v9.4.0/lib/node_modules/@aragon/cli/node_modules/merkle-patricia-tree/baseTrie.js:461:14
    at processNode (/home/bingen/.nvm/versions/node/v9.4.0/lib/node_modules/@aragon/cli/node_modules/merkle-patricia-tree/baseTrie.js:471:23)
    at /home/bingen/.nvm/versions/node/v9.4.0/lib/node_modules/@aragon/cli/node_modules/merkle-patricia-tree/baseTrie.js:516:13
    at /home/bingen/.nvm/versions/node/v9.4.0/lib/node_modules/@aragon/cli/node_modules/merkle-patricia-tree/baseTrie.js:180:7
    at /home/bingen/.nvm/versions/node/v9.4.0/lib/node_modules/@aragon/cli/node_modules/merkle-patricia-tree/util.js:75:7
    at /home/bingen/.nvm/versions/node/v9.4.0/lib/node_modules/@aragon/cli/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:52:16
    at /home/bingen/.nvm/versions/node/v9.4.0/lib/node_modules/@aragon/cli/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:269:32
    at /home/bingen/.nvm/versions/node/v9.4.0/lib/node_modules/@aragon/cli/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:44:16
    at /home/bingen/.nvm/versions/node/v9.4.0/lib/node_modules/@aragon/cli/node_modules/merkle-patricia-tree/util.js:71:7
    at /home/bingen/.nvm/versions/node/v9.4.0/lib/node_modules/@aragon/cli/node_modules/merkle-patricia-tree/baseTrie.js:157:9
    at /home/bingen/.nvm/versions/node/v9.4.0/lib/node_modules/@aragon/cli/node_modules/ganache-core/lib/database/levelupobjectadapter.js:30:23
    at /home/bingen/.nvm/versions/node/v9.4.0/lib/node_modules/@aragon/cli/node_modules/level-sublevel/shell.js:101:15
    at /home/bingen/.nvm/versions/node/v9.4.0/lib/node_modules/@aragon/cli/node_modules/level-sublevel/nut.js:121:19
    at /home/bingen/.nvm/versions/node/v9.4.0/lib/node_modules/@aragon/cli/node_modules/cachedown/index.js:58:21
    at ReadFileContext.callback (/home/bingen/.nvm/versions/node/v9.4.0/lib/node_modules/@aragon/cli/node_modules/ganache-core/lib/database/filedown.js:27:14)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:437:13)
```
I have seen this problem around, but haven't been able to fix it:
https://github.com/ethereumjs/merkle-patricia-tree/issues/12
https://github.com/dapphub/dapple/issues/337
https://gitter.im/ConsenSys/truffle?at=5901c500881b89e1018eadce
https://www.bountysource.com/issues/51180791-testrpc-crashes-after-a-while-with-cannot-read-property-pop-of-undefined-in-checkpointtrie-trie-_updatenode
https://github.com/trufflesuite/ganache-cli/issues/81

**Comment by alekspickle** [comment]
[Worked for me](https://github.com/aragon/aragen/issues/61), I'll just drop it here.
