### ISSUE TITLE
Error return doing dao apps on rinkeby

### ISSUE THREAD

**Issue by 0xGabi** [aragon/aragon-cli#1189]
## 🐛 Bug Report

`dao apps 0x7b8Bd3a3846cA13AC59aed917985E02c3c20c4b6 --env aragon:rinkeby`

Returns:
```
  ⠴ Inspecting DAO
    → Fetching apps for 0x7b8Bd3a3846cA13AC59aed917985E02c3c20c4b6...
Could not find repo for 0x818d8ea9df3dca764232c22548318a98f82f388b760b4b5abe80a4b40f9b2076 Error: ENS name not defined.
    at Object.<anonymous> (/Users/gabi/.nvm/versions/node/v11.15.0/lib/node_modules/@aragon/cli/node_modules/@aragon/toolkit/node_modules/ethjs-ens/index.js:15:23)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/Users/gabi/.nvm/versions/node/v11.15.0/lib/node_modules/@aragon/cli/node_modules/@aragon/toolkit/node_modules/aragon-cli-wrapper/dist/ens/index.js:1:72)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/Users/gabi/.nvm/versions/node/v11.15.0/lib/node_modules/@aragon/cli/node_modules/@aragon/toolkit/node_modules/ara  ✔ Inspecting DAO

✔ Successfully fetched DAO apps for 0x7b8Bd3a3846cA13AC59aed917985E02c3c20c4b6
```

Note the command works as expected nevertheless we output the above error.

**Comment by macor161** [comment]
Thanks @0xGabi ! I will have a look at this.

**Comment by macor161** [comment]
This seems to be a misconfigured DAO. I get the same error 
```
Could not find repo for 0x818d8ea9df3dca764232c22548318a98f82f388b760b4b5abe80a4b40f9b2076 Error: ENS name not defined.
```
when loading the organization from the frontend: https://rinkeby.aragon.org/#/0x7b8Bd3a3846cA13AC59aed917985E02c3c20c4b6
I will close this but feel free to let me know if this org is supposed to be working properly.
