### ISSUE TITLE
Error `Cannot find module 'web3-requestManager'` when doing `aragon run`

### ISSUE THREAD

**Issue by jtremback** [aragon/aragon-cli#146]
This was after doing 

```
$ npm i -g @aragon/cli
$ aragon init my_app_name34.aragonpm.eth
```

```bash
$ aragon run
 ✔ Start a local Ethereum network
 ✔ Check IPFS
 ❯ Publish app to APM
   ✔ Deploy contract
   ↓ Automatically bump version [skipped]
     → Starting from initial version
   ✔ Determine contract address for version
   ✖ Building frontend
     → Failed to build. See above output.
     Prepare files for publishing
     Generate application artifact
     Publish my_app_name34.aragonpm.eth
     Fetch published repo
   Create DAO
   Open DAO
 ✖ Command failed: yarn run build
module.js:549
    throw err;
    ^

Error: Cannot find module 'web3-requestManager'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/jehan/work/src/github.com/althea-mesh/try_aragon/my_app_name34/node_modules/web3/packages/web3-core/src/index.js:26:22)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! app-name@1.0.0 compile: `aragon contracts compile`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the app-name@1.0.0 compile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jehan/.npm/_logs/2018-06-21T21_39_28_863Z-debug.log
error Command failed with exit code 1.

yarn run v0.24.6
$ npm run compile && npm run sync-assets && npm run build:app && npm run build:script 

> app-name@1.0.0 compile /Users/jehan/work/src/github.com/althea-mesh/try_aragon/my_app_name34
> aragon contracts compile

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

module.js:549
    throw err;
    ^

Error: Cannot find module 'web3-requestManager'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/jehan/work/src/github.com/althea-mesh/try_aragon/my_app_name34/node_modules/web3/packages/web3-core/src/index.js:26:22)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! app-name@1.0.0 compile: `aragon contracts compile`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the app-name@1.0.0 compile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jehan/.npm/_logs/2018-06-21T21_39_28_863Z-debug.log
error Command failed with exit code 1.


Failed to build. See above output.

```

**Comment by jtremback** [comment]
I fixed this by doing `npm i @aragon/client` to install it to the folder I was working in, and then using `yarn start` to run it.

**Comment by jtremback** [comment]
This is probably due to me not running `npm install` before `aragon run`.

**Comment by luisivan** [comment]
Doing sanity check on this too at https://github.com/aragon/aragon-cli/issues/148#issuecomment-399344547
