### ISSUE TITLE
commands fail inside and Aragon app folder

### ISSUE THREAD

**Issue by macor161** [aragon/aragon-cli#1487]
## 🐛 Bug Report

**Bug currently in the `develop` branch.**

When running commands like `dao new`, `apm packages` or pretty much any commands inside an Aragon app project, it returns the following error: 

```
→ Didn't find any truffle.js file
✖ Error: Didn't find any truffle.js file
    at getTruffleConfig (aragon-cli/packages/toolkit/src/helpers/loadConfigFiles.js:86:9)
    at useEnvironment (aragon-cli/packages/toolkit/src/helpers/useEnvironment.js:105:7)
    at newDao (aragon-cli/packages/toolkit/src/dao/newDao.js:26:30)
```

**Comment by justinblair302** [comment]
To be explicit: until this fix is merged to master, the work around is to run the command from your home directory.
