### ISSUE TITLE
Cannot install @aragon/cli

### ISSUE THREAD

**Issue by vporton** [aragon/aragon-cli#1640]
## 🐛 Bug Report

```
yarn global add @aragon/cli
...
../src/node-boilerplate/inc/scrypt_params_async.h:38:39: error: no matching function for call to ‘v8::Value::IntegerValue()’
   38 |       osfreemem(info[3]->IntegerValue())
      |                                       ^
In file included from /home/porton/.cache/node-gyp/12.16.2/include/node/node.h:67,
                 from ../../nan/nan.h:56,
                 from ../src/node-boilerplate/scrypt_params_async.cc:1:
/home/porton/.cache/node-gyp/12.16.2/include/node/v8.h:2705:40: note: candidate: ‘v8::Maybe<long int> v8::Value::IntegerValue(v8::Local<v8::Context>) const’
 2705 |   V8_WARN_UNUSED_RESULT Maybe<int64_t> IntegerValue(
      |                                        ^~~~~~~~~~~~
/home/porton/.cache/node-gyp/12.16.2/include/node/v8.h:2705:40: note:   candidate expects 1 argument, 0 provided
../src/node-boilerplate/scrypt_params_async.cc: In member function ‘virtual void ScryptParamsAsyncWorker::HandleOKCallback()’:
../src/node-boilerplate/scrypt_params_async.cc:23:67: warning: ‘bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   23 |   obj->Set(Nan::New(\"N\").ToLocalChecked(), Nan::New<Integer>(logN));
      |                                                                   ^
In file included from /home/porton/.cache/node-gyp/12.16.2/include/node/v8-internal.h:14,
                 from /home/porton/.cache/node-gyp/12.16.2/include/node/v8.h:27,
                 from /home/porton/.cache/node-gyp/12.16.2/include/node/node.h:67,
                 from ../../nan/nan.h:56,
                 from ../src/node-boilerplate/scrypt_params_async.cc:1:
/home/porton/.cache/node-gyp/12.16.2/include/node/v8.h:3499:22: note: declared here
 3499 |                 bool Set(Local<Value> key, Local<Value> value));
      |                      ^~~
/home/porton/.cache/node-gyp/12.16.2/include/node/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’
  328 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
../src/node-boilerplate/scrypt_params_async.cc:24:64: warning: ‘bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   24 |   obj->Set(Nan::New(\"r\").ToLocalChecked(), Nan::New<Integer>(r));
      |                                                                ^
In file included from /home/porton/.cache/node-gyp/12.16.2/include/node/v8-internal.h:14,
                 from /home/porton/.cache/node-gyp/12.16.2/include/node/v8.h:27,
                 from /home/porton/.cache/node-gyp/12.16.2/include/node/node.h:67,
                 from ../../nan/nan.h:56,
                 from ../src/node-boilerplate/scrypt_params_async.cc:1:
/home/porton/.cache/node-gyp/12.16.2/include/node/v8.h:3499:22: note: declared here
 3499 |                 bool Set(Local<Value> key, Local<Value> value));
      |                      ^~~
/home/porton/.cache/node-gyp/12.16.2/include/node/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’
  328 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
../src/node-boilerplate/scrypt_params_async.cc:25:64: warning: ‘bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   25 |   obj->Set(Nan::New(\"p\").ToLocalChecked(), Nan::New<Integer>(p));
      |                                                                ^
In file included from /home/porton/.cache/node-gyp/12.16.2/include/node/v8-internal.h:14,
                 from /home/porton/.cache/node-gyp/12.16.2/include/node/v8.h:27,
                 from /home/porton/.cache/node-gyp/12.16.2/include/node/node.h:67,
                 from ../../nan/nan.h:56,
                 from ../src/node-boilerplate/scrypt_params_async.cc:1:
/home/porton/.cache/node-gyp/12.16.2/include/node/v8.h:3499:22: note: declared here
 3499 |                 bool Set(Local<Value> key, Local<Value> value));
      |                      ^~~
/home/porton/.cache/node-gyp/12.16.2/include/node/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’
  328 |   declarator __attribute__((deprecated(message)))
      |   ^~~~~~~~~~
../src/node-boilerplate/scrypt_params_async.cc:32:25: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
   32 |   callback->Call(2, argv);
      |                         ^
In file included from ../src/node-boilerplate/scrypt_params_async.cc:1:
../../nan/nan.h:1742:3: note: declared here
 1742 |   Call(int argc, v8::Local<v8::Value> argv[]) const {
      |   ^~~~
make: *** [scrypt.target.mk:131: Release/obj.target/scrypt/src/node-boilerplate/scrypt_params_async.o] Error 1
make: Leaving directory '/home/porton/.config/yarn/global/node_modules/scrypt/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/stow/node-v12.16.2-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.3.0-46-generic
gyp ERR! command \"/usr/local/stow/node-v12.16.2-linux-x64/bin/node\" \"/usr/local/stow/node-v12.16.2-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"
gyp ERR! cwd /home/porton/.config/yarn/global/node_modules/scrypt
gyp ERR! node -v v12.16.2
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok"
success Installed "@aragon/cli@7.0.3" with binaries:
      - aragon
      - dao
Done in 13.70s.
```

### Have you read the [Contributing Guidelines on issues](https://github.com/aragon/aragon-cli/blob/master/CONTRIBUTING.md#ways-to-contribute)?

- [x] Yes

node v12.16.2

**Comment by macor161** [comment]
Hi @vporton, the latest `@aragon/cli v7.1.5` should completely support yarn. Please also note that you may have to add the yarn global installation folder to your PATH. Feel free to reopen this issue if the problem still exists.
