### ISSUE TITLE
$ aragon run is failing on latest master

### ISSUE THREAD

**Issue by PascalPrecht** [aragon/aragon-cli#204]
Executing `$ aragon run` in the latest version (https://github.com/aragon/aragon-cli/commit/561ab2d629e0e705185f273e59ea3210d4182bd5 at the time of writing this issue) in newly scaffolded aragon app results in:

```
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the aragon@0.5.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pascalprecht/.npm/_logs/2018-09-12T08_47_46_669Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! aragon@0.5.0 start:local: `scripts/launch-local.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the aragon@0.5.0 start:local script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pascalprecht/.npm/_logs/2018-09-12T08_47_46_684Z-debug.log


> aragon@0.5.0 start:local /Users/pascalprecht/.aragon/wrapper-fcebf55d1af6c574a92587e2a1d3ac8c00804d16
> scripts/launch-local.sh

Running aragon/aragon on local environment settings...

Found a local IPFS daemon running...
The app will be configured to connect and serve assets from from the default gateway (http://localhost:8080/ipfs).
Also defaulting the asset bridge to IPFS.


> aragon@0.5.0 start /Users/pascalprecht/.aragon/wrapper-fcebf55d1af6c574a92587e2a1d3ac8c00804d16
> npm run ui-assets && parcel serve src/index.html --port 3000 --out-dir ./build --no-cache


> aragon@0.5.0 ui-assets /Users/pascalprecht/.aragon/wrapper-fcebf55d1af6c574a92587e2a1d3ac8c00804d16
> copy-aragon-ui-assets -n aragon-ui ./build


    at /Users/pascalprecht/projects/aragon/aragon-cli/dist/commands/run.js:449:29
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:78675) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:78675) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

I first thought this had something to do with the version of the aragon client being checked out by the CLI. However, it turns out that it doesn't matter whether the currently hardcoded wrapper commit `fcebf55d1af6c574a92587e2a1d3ac8c00804d16` or `master` of aragon/aragon is used. This can be verified by using a custom locally installed version of the client by using the `--client-path` option of the CLI that is enabled in this commit: https://github.com/aragon/aragon-cli/pull/200/commits/41a6a04b834c643e97fd04d1701ad22d45e801eb

Switching to a different version of the CLI however, does solve the issue so there seems to be something between 4.x and 5.0.0 that causes this issue.

I'm gonna bisect it to see which commit introduced this.

**Comment by PascalPrecht** [comment]
Okay, turns out this commit causes it: https://github.com/aragon/aragon-cli/commit/e3d01b12b7b202459bd80b6e02b1e3d91f76a301

Which is really just the change of the wrapper commit. So the actual bug is in the wrapper repository. Need to investigate more...

**Comment by rperez89** [comment]
Hi @PascalPrecht i am having the same issue! how do you solve it? i am just runing npm run start

**Comment by rperez89** [comment]
and that happened to me trying to run the : https://github.com/aragon/aragon-react-kit-boilerplate

**Comment by Quazia** [comment]
I would try ``rm -rf ~/.aragon`` and then try the solution [here](https://github.com/aragon/aragon-cli/issues/215#issuecomment-425837204). Let me know if you're still having an issue.

**Comment by rperez89** [comment]
@Quazia thanks for your answer, i did it and i am still getting conflicting babel versions found
