### ISSUE TITLE
Error: Cannot find module './build/Release/scrypt' when running aragon init

### ISSUE THREAD

**Issue by Bowfish** [aragon/aragon-cli#225]
I just installed aragon-cli. 

When I run the command `aragon init foo.aragonpm.eth react` I get the following error message:

```javascript
module.js:549
    throw err;
    ^

Error: Cannot find module './build/Release/scrypt'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/@aragon/cli/node_modules/scrypt/index.js:3:20)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
`
What am I doing wrong here?

**Comment by sohkai** [comment]
@Bowfish Could you try installing the latest version (`5.2.0`) and try again?

**Comment by sudhiryadav** [comment]
change this line require("./build/Release/scrypt") to require("scrypt") from '/node_modules/scrypt/index.js'

**Comment by sohkai** [comment]
@0x6431346e Wondering if we can close this, since we're pointing people to use `create-aragon-app` instead?

**Comment by davidmimay** [comment]
> change this line require("./build/Release/scrypt") to require("scrypt") from '/node_modules/scrypt/index.js'

that works for me, thank you!
