### ISSUE TITLE
dao acl [address] cannot print table

### ISSUE THREAD

**Issue by 0x6431346e** [aragon/aragon-cli#271]
```
% dao acl 0x035ba8048C4Ab2d9478dFE3b56d09fE1c6538438 --debug                                                                                                                                        ❯ ["/home/daniel/.nvm/versions/node/v11.0.0/bin/node","/home/daniel/.nvm/versions/node/v11.0.0/bin/aragon","dao","acl","0x035ba8048C4Ab2d9478dFE3b56d09fE1c6538438","--debug"]
[14:16:20] Inspecting DAO Permissions [started]
[14:16:20] → Fetching permissions for 0x035ba8048C4Ab2d9478dFE3b56d09fE1c6538438...
[14:16:20] Inspecting DAO Permissions [completed]
 ✔ Successfully fetched DAO apps for 0x035ba8048C4Ab2d9478dFE3b56d09fE1c6538438
 ✖ Cannot read property 'toString' of undefined
 ❯ TypeError: Cannot read property 'toString' of undefined
    at /home/daniel/repos/aragon/aragon-cli/node_modules/cli-table/lib/index.js:182:27
    at Array.forEach (<anonymous>)
    at generateRow (/home/daniel/repos/aragon/aragon-cli/node_modules/cli-table/lib/index.js:181:11)
    at Table.toString (/home/daniel/repos/aragon/aragon-cli/node_modules/cli-table/lib/index.js:254:12)
    at /home/daniel/repos/aragon/aragon-cli/dist/commands/dao_cmds/acl_cmds/view.js:154:33
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
```

**Comment by sohkai** [comment]
Closed with #252.
