### ISSUE TITLE
aragon devchain fails while starting

### ISSUE THREAD

**Issue by tommycox** [aragon/aragon-cli#281]
Mac OSX. Tested on fresh npm install of `@aragon/cli` using node v8.14.0 and v10.14.1. Also affects `aragon run`

```shell
 ~ > aragon -v
5.2.1
 ~ > aragon devchain
 ⠙ Local chain started at port 8545
undefined:1



SyntaxError: Unexpected end of JSON input
    at Object.parse [as decode] (<anonymous>)
    at Object.decodeValue (/Users/cryptotom/.nvm/versions/node/v10.14.1/lib/node_modules/@aragon/cli/node_modules/ganache-core/node_modules/level-sublevel/node_modules/levelup/lib/codec.js:53:35)
    at /Users/cryptotom/.nvm/versions/node/v10.14.1/lib/node_modules/@aragon/cli/node_modules/ganache-core/node_modules/level-sublevel/nut.js:122:34
    at /Users/cryptotom/.nvm/versions/node/v10.14.1/lib/node_modules/@aragon/cli/node_modules/ganache-core/node_modules/cachedown/index.js:61:5
    at /Users/cryptotom/.nvm/versions/node/v10.14.1/lib/node_modules/@aragon/cli/node_modules/ganache-core/lib/database/filedown.js:29:5
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
```

**Comment by tommycox** [comment]
A fresh install on an Ubuntu machine had no issue 😕

**Comment by sohkai** [comment]
@tommycox You might also have some luck by removing the `~/.aragon` directory, if you had previously installed a different version before.

**Comment by tommycox** [comment]
Ah ha! That did the trick, thanks @sohkai 🎉
