### ISSUE TITLE
query returned more than 1000 results

### ISSUE THREAD

**Issue by 0x6431346e** [aragon/aragon-cli#522]
## 🐛 Bug Report

As reported by @AlexanderMazaletskiy

```
aragon apm publish major 0xa406aa3e2cb8606556d06a0bae206cf59a1a74e3 --environment rinkeby
✔ Check IPFS
✔ Applying version bump (major)
✔ Compile contracts
✔ Determine contract address for version
↓ Building frontend [skipped]
→ Build script not defined in package.json
✔ Prepare files for publishing
✔ Generate application artifact
❯ Publish democracy-akropolis.open.aragonpm.eth
⠙ Generating transaction
→ Fetching DAO at 0x2DF31C5fcBB94656fc98e2953cF0DA03e2885Cfa...
Sending transaction
Fetch published repo

/Users/alexandermazaletskiy/Documents/Akropolis/dao-kits/kits/democracy/node_modules/truffle-hdwallet-provider-privkey/node_modules/web3/lib/web3/httpprovider.js:129
callback(error, result);
^
Error: query returned more than 1000 results
at /Users/alexandermazaletskiy/Documents/Akropolis/dao-kits/kits/democracy/node_modules/truffle-hdwallet-provider-privkey/node_modules/web3-provider-engine/subproviders/web3.js:15:44
at XMLHttpRequest.request.onreadystatechange (/Users/alexandermazaletskiy/Documents/Akropolis/dao-kits/kits/democracy/node_modules/truffle-hdwallet-provider-privkey/node_modules/web3/lib/web3/httpprovider.js:129:7)
at XMLHttpRequestEventTarget.dispatchEvent (/Users/alexandermazaletskiy/Documents/Akropolis/dao-kits/kits/democracy/node_modules/xhr2-cookies/xml-http-request-event-target.ts:44:13)
at XMLHttpRequest._setReadyState (/Users/alexandermazaletskiy/Documents/Akropolis/dao-kits/kits/democracy/node_modules/xhr2-cookies/xml-http-request.ts:219:8)
at XMLHttpRequest._onHttpResponseEnd (/Users/alexandermazaletskiy/Documents/Akropolis/dao-kits/kits/democracy/node_modules/xhr2-cookies/xml-http-request.ts:345:8)
at IncomingMessage.<anonymous> (/Users/alexandermazaletskiy/Documents/Akropolis/dao-kits/kits/democracy/node_modules/xhr2-cookies/xml-http-request.ts:311:39)
at IncomingMessage.emit (events.js:194:15)
at endReadableNT (_stream_readable.js:1125:12)
at process._tickCallback (internal/process/next_tick.js:63:19)
MacBook-2:democracy alexandermazaletskiy$ 

Error: query returned more than 1000 results. Do you know what is it?
```

https://community.infura.io/t/getlogs-error-query-returned-more-than-1000-results/358/9

aragonCLI v5.9.4

repo: https://github.com/akropolisio/dao-kits

**Comment by 0x6431346e** [comment]
I was not able to reproduce it, in my case it would get stuck here:

```
  ❯ Publish democracy-akropolis.open.aragonpm.eth
    ⠇ Generating transaction
      → Fetching DAO at 0x2DF31C5fcBB94656fc98e2953cF0DA03e2885Cfa...
      Sending transaction
```

and that is because we need a websockets rpc to read events from:

```diff
    "rinkeby": {
      "registry": "0x98Df287B6C145399Aaa709692c8D308357bC085D",
      "appName": "democracy-akropolis-test.open.aragonpm.eth",
+     "wsRPC": "wss://rinkeby.eth.aragon.network/ws",
      "network": "rinkeby"
    },
```

After this change I could deploy successfully:

```
  ✔ Check IPFS
  ✔ Applying version bump (major)
  ✔ Compile contracts
  ✔ Determine contract address for version
  ↓ Building frontend [skipped]
    → Build script not defined in package.json
  ✔ Prepare files for publishing
  ✔ Generate application artifact
  ✔ Publish democracy-akropolis-test.open.aragonpm.eth
  ✔ Fetch published repo

 ✔ Successfully published democracy-akropolis-test.open.aragonpm.eth v2.0.0: 
 ℹ Contract address: 0xa406aa3E2cb8606556d06A0bae206Cf59A1A74E3
 ℹ Content (ipfs): QmPJqoCgyVVucUypvZ4ruZtjnJ1uBWksjej2kdqzJpomZs
 ℹ Transaction hash: 0x5f4b0127ab104c39a59ee2f21c800c96a5dc3206ff8e4799d0586ab381119f2b
```

**Comment by 0xGabi** [comment]
I think we can close this one now. Feel free to open again if a new issue arraise
