### ISSUE TITLE
TypeError: Cannot read property 'pop' of undefined

### ISSUE THREAD

**Issue by 0x6431346e** [aragon/aragon-cli#551]
## 🐛 Bug Report

```sh
realisations-MacBook-Pro:etude realisation$ aragon devchain --debug 
Starting a local chain from snapshot [started]
Local chain started at port 8545 [title changed]

/Users/realisation/.nvm/versions/node/v11.12.0/lib/node_modules/@aragon/cli/node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:360
  var lastNode = stack.pop()
                       ^
TypeError: Cannot read property 'pop' of undefined
    at CheckpointTrie.Trie._updateNode (/Users/realisation/.nvm/versions/node/v11.12.0/lib/node_modules/@aragon/cli/node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:360:24)
    at /Users/realisation/.nvm/versions/node/v11.12.0/lib/node_modules/@aragon/cli/node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:107:16
```

**Comment by 0x6431346e** [comment]
I've just stumbled upon this as well when working on https://github.com/aragon/aragon-cli/pull/545 .

For context: I was killing the process abruptly and often which probably caused a writing process to not finish.

Solved it by deleting `~/.aragon/aragen-db-4.2.0` .

If that doesn't work, perhaps a more thorough cleanup:
```
rm -rf ~/.aragon
npm uninstall --global @aragon/cli
npm install --global @aragon/cli
aragon devchain
```

An `aragon reset/clean` command would be nice for this type of things

**Comment by realisation** [comment]
This doesn't solve it for me. Doing it both of the ways gives me the same behavior:

After running `rm -rf ~/.aragon/aragen-db-4.2.0` or `rm -rf ~/.aragon && npm uninstall --global @aragon/cli && npm install --global @aragon/cli`, then running `argaon devchain`, I get the following error: 
```
  ✔ Setting up a new chain from latest Aragon snapshot
  ✖ Local chain started at port 8545
    → Cannot read property 'secretKey' of undefined
 ✖ Cannot read property 'secretKey' of undefined
```

And after that, if I run `aragon devchain` again, I get the original error raised in this issue.

**Comment by 0x6431346e** [comment]
> This doesn't solve it for me. Doing it both of the ways gives me the same behavior:
> 
> After running `rm -rf ~/.aragon/aragen-db-4.2.0` or `rm -rf ~/.aragon && npm uninstall --global @aragon/cli && npm install --global @aragon/cli`, then running `argaon devchain`, I get the following error:
> 
> ```
>   ✔ Setting up a new chain from latest Aragon snapshot
>   ✖ Local chain started at port 8545
>     → Cannot read property 'secretKey' of undefined
>  ✖ Cannot read property 'secretKey' of undefined
> ```
> 
> And after that, if I run `aragon devchain` again, I get the original error raised in this issue.

I really don't know how to replicate it again :/
Any tips for me ?

**Comment by realisation** [comment]
I'm just doing it as described so there's not many things I could do differently.

I uninstall @aragon/cli and create-aragon-app and reinstalled them, same result. 

I built from source with and npm linked the dependency, same result. 

I even checked out the tag v5.10.0 source, installed ganache-core@2.2.1 and npm linked that build as @0xGabi suggested to me and still encountered the same issue.

I tried checking out the LTS node version 10.16.0 and when I tried to run `npx aragon` after redoing my local build and npm linking it to my app directory it said it was compiled against another version of node :/

**Comment by 0x6431346e** [comment]
> I tried checking out the LTS node version 10.16.0 and when I tried to run `npx aragon` after redoing my local build and npm linking it to my app directory it said it was compiled against another version of node :/

That's because you need to re-install the dependencies:
```
npm run clean
npm install
``` 
This is because some dependencies are native.

As far as node versions go, I'm using 11, our [CI builds successfully 8,9,10,11](https://travis-ci.org/aragon/aragon-cli/builds/551543424?utm_source=github_status&utm_medium=notification) and AFAIK nobody else is reported a similar issue... 

Perhaps the npm cache is corrupted? :confused: 
```
rm -rf ~/.aragon
npm uninstall --global @aragon/cli
npm cache clean --force
npm install --global @aragon/cli
aragon devchain
```

Do other commands work btw?

**Comment by realisation** [comment]
I did reinstall the dependencies, by rm -rf'ing the node modules folder..

**Comment by realisation** [comment]
The help command works. I haven't tried other ones than that

**Comment by 0x6431346e** [comment]
Update: seems to work with 

`npx @aragon/aragen@4.1.2 devchain`

Must be something in version 4.2.0...
