### ISSUE TITLE
Fetching DAO transaction error

### ISSUE THREAD

**Issue by svetlanama** [aragon/aragon-cli#554]
Hi, 
I started getting a new error while trying to publish token-wrapper app
network: Rinkeby
command: ```aragon apm publish major --environment staging --files app/build```

I've re-installed aragon-cli and reset all related folders 
I've repeated installation about 7 times and the error is stable
Last week I have no error with this installation

Here is an output
```
  ✔ Check IPFS
  ✔ Applying version bump (major)
  ✔ Deploy contract
  ✔ Determine contract address for version
  ✔ Building frontend
  ✔ Prepare files for publishing
  ✔ Generate application artifact
  ❯ Publish pitch4-token-wrapper.open.aragonpm.eth
    ⠹ Generating transaction
      → Fetching DAO at 0x2DF31C5fcBB94656fc98e2953cF0DA03e2885Cfa...
      Sending transaction
    Fetch published repo
 ✖ Error inspecting DAO
```

Appreciate if you could help.

**Comment by svetlanama** [comment]
It works now, closed the issue!

**Comment by sembrestels** [comment]
This issue is hitting again. More specifically it can't connect on WS when inspecting the APM DAO:

```
npx aragon dao apps 0x2DF31C5fcBB94656fc98e2953cF0DA03e2885Cfa --environment rinkeby --debug
❯ aragonCLI version: 6.4.1
❯ argv: ["/usr/local/bin/node","/home/sem/Projects/committees/node_modules/.bin/aragon","dao","apps","0x2DF31C5fcBB94656fc98e2953cF0DA03e2885Cfa","--environment","rinkeby","--debug"]
Inspecting DAO [started]
→ Fetching apps for 0x2DF31C5fcBB94656fc98e2953cF0DA03e2885Cfa...
Redefining LocalForage driver: memoryStorageDriver
✖ Error inspecting DAO apps
❯ Error: CONNECTION ERROR: Couldn't connect to node on WS.
    at Object.InvalidConnection (/home/sem/Projects/committees/node_modules/@aragon/cli/node_modules/web3-core-helpers/src/errors.js:35:16)
    at WebsocketProvider._timeout (/home/sem/Projects/committees/node_modules/@aragon/cli/node_modules/web3-providers-ws/src/index.js:255:48)
    at W3CWebSocket.connection.onclose (/home/sem/Projects/committees/node_modules/@aragon/cli/node_modules/web3-providers-ws/src/index.js:155:15)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/home/sem/Projects/committees/node_modules/@aragon/cli/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onClose (/home/sem/Projects/committees/node_modules/@aragon/cli/node_modules/web3-providers-ws/node_modules/websocket/lib/W3CWebSocket.js:228:10)
    at WebSocketConnection.<anonymous> (/home/sem/Projects/committees/node_modules/@aragon/cli/node_modules/web3-providers-ws/node_modules/websocket/lib/W3CWebSocket.js:201:17)
    at WebSocketConnection.emit (events.js:198:13)
    at WebSocketConnection.drop (/home/sem/Projects/committees/node_modules/@aragon/cli/node_modules/web3-providers-ws/node_modules/websocket/lib/WebSocketConnection.js:475:14)
    at /home/sem/Projects/committees/node_modules/@aragon/cli/node_modules/web3-providers-ws/node_modules/websocket/lib/WebSocketConnection.js:303:18
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

**Comment by vporton** [comment]
The issue is hitting again:

When I use wss://rinkeby.eth.aragon.network/ws I get:

```
$ npx aragon dao apps 0x2DF31C5fcBB94656fc98e2953cF0DA03e2885Cfa --environment rinkeby --debug
❯ aragonCLI version: 7.0.3
❯ argv: ["/usr/bin/node","/home/porton/Projects/courts/node_modules/.bin/aragon","dao","apps","0x2DF31C5fcBB94656fc98e2953cF0DA03e2885Cfa","--environment","rinkeby","--debug"]
Inspecting DAO [started]
→ Fetching apps for 0x2DF31C5fcBB94656fc98e2953cF0DA03e2885Cfa...
Redefining LocalForage driver: memoryStorageDriver
Inspecting DAO [failed]
→ CONNECTION ERROR: Couldn't connect to node on WS.
✖ Error: CONNECTION ERROR: Couldn't connect to node on WS.
    at Object.InvalidConnection (/home/porton/Projects/courts/node_modules/@aragon/cli/node_modules/web3/node_modules/web3-core-helpers/src/errors.js:35:16)
    at WebsocketProvider._timeout (/home/porton/Projects/courts/node_modules/@aragon/cli/node_modules/web3/node_modules/web3-providers-ws/src/index.js:255:48)
    at W3CWebSocket.connection.onclose (/home/porton/Projects/courts/node_modules/@aragon/cli/node_modules/web3/node_modules/web3-providers-ws/src/index.js:155:15)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/home/porton/Projects/courts/node_modules/@aragon/cli/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onClose (/home/porton/Projects/courts/node_modules/@aragon/cli/node_modules/@web3-js/websocket/lib/W3CWebSocket.js:228:10)
    at WebSocketConnection.<anonymous> (/home/porton/Projects/courts/node_modules/@aragon/cli/node_modules/@web3-js/websocket/lib/W3CWebSocket.js:201:17)
    at WebSocketConnection.emit (events.js:189:13)
    at WebSocketConnection.drop (/home/porton/Projects/courts/node_modules/@aragon/cli/node_modules/@web3-js/websocket/lib/WebSocketConnection.js:475:14)
    at /home/porton/Projects/courts/node_modules/@aragon/cli/node_modules/@web3-js/websocket/lib/WebSocketConnection.js:303:18
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

If I instead use https://rinkeby.infura.io/v3/rewardcourts in the `arapp.json`, I get:

```
$ npx aragon dao apps 0x2DF31C5fcBB94656fc98e2953cF0DA03e2885Cfa --environment rinkeby --debug
❯ aragonCLI version: 7.0.3
❯ argv: ["/usr/bin/node","/home/porton/Projects/courts/node_modules/.bin/aragon","dao","apps","0x2DF31C5fcBB94656fc98e2953cF0DA03e2885Cfa","--environment","rinkeby","--debug"]
Inspecting DAO [started]
→ Fetching apps for 0x2DF31C5fcBB94656fc98e2953cF0DA03e2885Cfa...
connection not open on send()
Inspecting DAO [failed]
→ Provided daoAddress is not a DAO
✖ Error: Provided daoAddress is not a DAO
    at Aragon.Error [as init] (/home/porton/Projects/courts/node_modules/@aragon/cli/node_modules/@aragon/toolkit/node_modules/aragon-cli-wrapper/src/index.js:183:13)
```
