### ISSUE TITLE
Solc optimizer crashing on Linux nodejs 11 (via aragon run)

### ISSUE THREAD

**Issue by macor161** [aragon/aragon-cli#731]
### Have you read the [Contributing Guidelines on issues](https://github.com/aragon/aragon-cli/blob/master/CONTRIBUTING.md#ways-to-contribute)?

Yes

#### Environment

- Ubuntu 19.04
- Node.js 11
- @aragon/cli 6.2.5
- create-aragon-app 2.2.14

## To Reproduce

```
npx create-aragon-app test
cd test
aragon run
```

## Expected behavior

Compile and deploy the app

## Actual Behavior

Crashes with the following output:

```
  ✔ Check port
  ✔ Running prepublish script
  ✔ Running prepublish script
  ✔ Applying version bump (major)
  ✔ Building frontend
  ❯ Deploy contract
    ⠋ Compile contracts
/home/mathew_corm/.nvm/versions/node/v11.15.0/lib/node_modules/@aragon/cli/node_modules/truffle/node_modules/solc/soljson.js:12
RangeError: Maximum call stack size exceeded
    at Object._db [as dynCall_viiiiii] (/home/mathew_corm/.nvm/versions/node/v11.15.0/lib/node_modules/@aragon/cli/node_modules/truffle/node_modules/solc/soljson.js:12:120931)
    at invoke_viiiiii (/home/mathew_corm/.nvm/versions/node/v11.15.0/lib/node_modules/@aragon/cli/node_modules/truffle/node_modules/solc/soljson.js:1:1117622)
    at Array.ova (/home/mathew_corm/.nvm/versions/node/v11.15.0/lib/node_modules/@aragon/cli/node_modules/truffle/node_modules/solc/soljson.js:13:29030)
    at Object.L9a [as dynCall_vi] (/home/mathew_corm/.nvm/versions/node/v11.15.0/lib/node_modules/@aragon/cli/node_modules/truffle/node_modules/solc/soljson.js:12:99033)
    at invoke_vi (/home/mathew_corm/.nvm/versions/node/v11.15.0/lib/node_modules/@aragon/cli/node_modules/truffle/node_modules/solc/soljson.js:1:1114426)
    at Array.wta (/home/mathew_corm/.nvm/versions/node/v11.15.0/lib/node_modules/@aragon/cli/node_modules/truffle/node_modules/solc/soljson.js:10:704789)
    at Object.Cfb [as dynCall_iii] (/home/mathew_corm/.nvm/versions/node/v11.15.0/lib/node_modules/@aragon/cli/node_modules/truffle/node_modules/solc/soljson.js:12:130740)
    at invoke_iii (/home/mathew_corm/.nvm/versions/node/v11.15.0/lib/node_modules/@aragon/cli/node_modules/truffle/node_modules/solc/soljson.js:1:1118857)
    at Array.uta (/home/mathew_corm/.nvm/versions/node/v11.15.0/lib/node_modules/@aragon/cli/node_modules/truffle/node_modules/solc/soljson.js:10:703085)
    at Object.Xfb [as dynCall_iiiiii] (/home/mathew_corm/.nvm/versions/node/v11.15.0/lib/node_modules/@aragon/cli/node_modules/truffle/node_modules/solc/soljson.js:12:131900)```

**Comment by sohkai** [comment]
I think there were some reports on rocket chat of this happening to the aragon-apps as well; @macor161 could you try cloning aragon-apps and seeing if they install and compile correctly?

**Comment by macor161** [comment]
So after doing further tests, part of the problem seems to be within truffle 4. I get the same error when I try to compile `aragon-react-boilerplate` with truffle `4.1.14`. Everything is compiling fine with truffle 5 however, so the bug should be fixed when the CLI upgrades its truffle dependency.

Oddly enough, the problem started when the aragonOS `truffle.json` was imported in https://github.com/aragon/aragon-react-boilerplate/commit/3f4159d0c99ca1d39c485f05be2ed4a8baa8c0ac
Specifically, enabling the optimizer caused the problem, which is quite weird.

In any case, a fix for linux users using `node.js 11` would be to simply disable the optimizer. The following modification did the trick for me:

```
module.exports = require('@aragon/os/truffle-config')
module.exports.solc.optimizer.enabled = false
```

**Comment by sohkai** [comment]
Thanks for the research @macor161! This sounds like a great reason to upgrade to truffle 5 😄

Did you have the optimizer also enabled when trying truffle 5? If I remember they might have used slightly different configuration so the optimizer may not have been running on truffle 5).

**Comment by macor161** [comment]
@sohkai Yep optimizer enabled with `10000`runs

**Comment by 0xGabi** [comment]
Related to #719

**Comment by 0xGabi** [comment]
Now that we are using truffle 5 I'll close this one
