### ISSUE TITLE
Issues with IPFS init when local instance installed through SNAP

### ISSUE THREAD

**Issue by Quazia** [aragon/aragon-cli#744]
## 🐛 Bug Report

Currently when checking if IPFS has been initaited the check is whether `.ipfs` exists at the home directory, depending on how IPFS is installed this might not be the correct location to check in order to know if IPFS has been installed. As a work-around you can just `touch ~/.ipfs` and everything works fine but this doesn't seem like a good long term solution.

### Have you read the [Contributing Guidelines on issues](https://github.com/aragon/aragon-cli/blob/master/CONTRIBUTING.md#ways-to-contribute)?

Yes

#### Mainnet or testnet?

Testnet

#### Organization

Autark

#### Environment

- OS and OS version: [e.g. Linux Mint 18.0]
- Browser and browser version: [e.g. Firefox 64.0]
- Add any other context about the problem here.

## To Reproduce

Install IPFS using SNAP
Run `aragon ipfs`

## Expected behavior

IPFS would run without trying to re-initialize

## Actual Behavior

```
  ⠸ Start IPFS
    → Starting IPFS at port: 5001
    Add local files
(node:29116) UnhandledPromiseRejectionWarning: Error: Command failed: /snap/bin/ipfs init
Error: ipfs configuration file already exists!
Reinitializing would overwrite your keys.


initializing IPFS node at /home/q/snap/ipfs/1170/.ipfs

    at makeError (/home/q/.nvm/versions/node/v10.11.0/lib/node_modules/@aragon/cli/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/home/q/.nvm/versions/node/v10.11.0/lib/node_modules/@aragon/cli/node_modules/execa/index.js:278:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  ✖ Start IPFS
    → Starting IPFS timed out:
    Add local files
✖ Starting IPFS timed out:
```

**Comment by sohkai** [comment]
@0x6431346e @0xGabi Wondering if we should change the IPFS check to do a `which ipfs` instead of the config file?

**Comment by 0xGabi** [comment]
@dapplion you consider is this solution still useful or should we look to solve #744 other way?

**Comment by dapplion** [comment]
The intention is to use https://github.com/ipfs/js-ipfsd-ctl which handles all the configuration in a disposable way and therefore this should not be a problem

**Comment by sohkai** [comment]
Just wondering on the above; I'm not sure if we would be able to rely entirely on a disposable IPFS instance since we need the IPFS content generated by the publishing process to be long-lived somewhere.
