### ISSUE TITLE
`npx create-aragon-app reward` crashes

### ISSUE THREAD

**Issue by vporton** [aragon/aragon-cli#899]
## 🐛 Bug Report

```
$ npx create-aragon-app reward
  ✔ Preparing initialization
  ✔ Cloning app template
  ✔ Preparing template
  ✖ Installing package dependencies
    → Failed to install dependencies. See above output.
    Check IPFS
✖ Command failed: npm install
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'umask'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/usr/share/npm/lib/utils/umask.js:1:75)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)


internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'umask'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/usr/share/npm/lib/utils/umask.js:1:75)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)


Failed to install dependencies. See above output.
```

### Have you read the [Contributing Guidelines on issues](https://github.com/aragon/aragon-cli/blob/master/CONTRIBUTING.md#ways-to-contribute)?

Yes.

#### Environment

- OS and OS version: Ubuntu 19.10
- Browser and browser version: none
- Add any other context about the problem here.

Linux victor-pc 5.3.0-19-generic #20-Ubuntu SMP Fri Oct 18 09:04:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

## To Reproduce

See above.

## Actual Behavior

Crash.

**Comment by vporton** [comment]
Note that `npm install umask` does not help.

**Comment by macor161** [comment]
Hi @vporton can you give me your nodejs version?

**Comment by 0xGabi** [comment]
No relevant

**Comment by vporton** [comment]
`npm i npm` solved the trouble.
