### ISSUE TITLE
`dao exec`: exports.task is not a function

### ISSUE THREAD

**Issue by xuhcc** [aragon/aragon-cli#919]
## 🐛 Bug Report

`dao exec` command started to fail after upgrading to version 6.4.0.

### Have you read the [Contributing Guidelines on issues](https://github.com/aragon/aragon-cli/blob/master/CONTRIBUTING.md#ways-to-contribute)?

Yes.

#### Mainnet or testnet?

Any.

#### Organization

Any.

#### Environment

- OS and OS version: Arch Linux
- Browser and browser version: N/A
- aragon-cli: **6.4.0**

## To Reproduce

Run `dao exec` with any arguments. For example:

```
dao exec 0x 0x vote --environment aragon:rinkeby --debug
```

## Expected behavior

The command should run without errors.

## Actual Behavior

```
$ dao exec 0x 0x vote --environment aragon:rinkeby --debug
❯ aragonCLI version: 6.4.0
❯ argv: ["/usr/bin/node","/usr/bin/aragon","dao","exec","0x","0x","vote","--environment","aragon:rinkeby","--debug"]
❯ Could not find 'arapp.json'. Using the default configuration to connect to rinkeby.
✖ exports.task is not a function
❯ TypeError: exports.task is not a function
    at task (/usr/lib/node_modules/@aragon/cli/src/commands/dao_cmds/utils/execHandler.js:122:31)
    at tryCatch (/usr/lib/node_modules/@aragon/cli/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/usr/lib/node_modules/@aragon/cli/node_modules/regenerator-runtime/runtime.js:271:22)
    at Generator.prototype.(anonymous function) [as next] (/usr/lib/node_modules/@aragon/cli/node_modules/regenerator-runtime/runtime.js:97:21)
    at tryCatch (/usr/lib/node_modules/@aragon/cli/node_modules/regenerator-runtime/runtime.js:45:40)
    at invoke (/usr/lib/node_modules/@aragon/cli/node_modules/regenerator-runtime/runtime.js:135:20)
    at /usr/lib/node_modules/@aragon/cli/node_modules/regenerator-runtime/runtime.js:145:13
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by xuhcc** [comment]
`dao act` is also broken in 6.4.0, let me know if I should submit a separate bug report for it:

```
✖ Cannot read property 'abi' of undefined
```

**Comment by 0xGabi** [comment]
Thanks for the quick report @xuhcc We merged a fix and will release a new patch version with the changes
